GET https://localhost:4000/ HTTP/1.1

###

GET https://localhost:4000/snippet/view/31 HTTP/1.1

###

POST https://localhost:4000/snippet/create HTTP/1.1
Content-Type: application/x-www-form-urlencoded

title=foo
&content=bar
&expires=7

###

GET https://localhost:4000/download HTTP/1.1
