name: '[1] Build and Test'
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub
        uses: actions/checkout@v4

      - name: Start MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8mb4'
          collation server: 'utf8mb4_unicode_ci'
          mysql database: 'test_snippetbox'
          mysql root password: 'pass'

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          
      - name: Install Dependencies
        run: go get -d -v ./...

      - name: Build
        run: go build -v ./...

      - name: Test with the Go CLI
        run: go test -v ./...
