name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8mb4'
          collation server: 'utf8mb4_unicode_ci'
          mysql database: 'test_snippetbox'
          mysql root password: 'pass'

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          
      - name: Install dependencies
        run: go get -d -v ./...

      - name: Build
        run: |
          echo $PWD
          ls -l
          go build -v ./...

      - name: Test with the Go CLI
        run: |
          echo $PWD
          ls -l
          go test -v ./...
